[environments.development]
theme = "Dawn test"
store = "flagship-store-test"
password  = "shptka_d06e255a41df88dc2645ea02e72b0710"
ignore = ""
[environments.env2]
store = "another-store"
path = "./dist"
ignore = ["sections/announcement-bar.liquid", "sections/header.liquid"]
output = "json"
live = true
allow-live = true